// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc.team3219.robot;

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS
import com.ctre.phoenix.motorcontrol.can.WPI_TalonSRX;

import edu.wpi.first.wpilibj.Encoder;
import edu.wpi.first.wpilibj.PowerDistributionPanel;
import edu.wpi.first.wpilibj.SpeedControllerGroup;
import edu.wpi.first.wpilibj.drive.DifferentialDrive;

// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS
import edu.wpi.first.wpilibj.livewindow.LiveWindow;

/**
 * The RobotMap is a mapping from the ports sensors and actuators are wired into
 * to a variable name. This provides flexibility changing wiring, makes checking
 * the wiring easier and significantly reduces the number of magic numbers
 * floating around.
 */
public class RobotMap {
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    public static WPI_TalonSRX driveTrainFrontLeft;
    public static WPI_TalonSRX driveTrainBackLeft;
    public static SpeedControllerGroup driveTrainLeftDrive;
    public static Encoder leftEncoder;
    public static WPI_TalonSRX driveTrainFrontRight;
    public static WPI_TalonSRX driveTrainBackRight;
    public static SpeedControllerGroup driveTrainRightDrive;
    public static Encoder rightEncoder;
    public static DifferentialDrive driveTrainDifferentialDrive1;
    public static PowerDistributionPanel powerManagmentPowerDistributionPanel;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS

    public static void init() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
        driveTrainFrontLeft = new WPI_TalonSRX(1);
        
        
        driveTrainBackLeft = new WPI_TalonSRX(2);
        
        
        driveTrainLeftDrive = new SpeedControllerGroup(driveTrainFrontLeft, driveTrainBackLeft  );
        LiveWindow.addActuator("DriveTrain", "LeftDrive", driveTrainLeftDrive);
        
        driveTrainFrontRight = new WPI_TalonSRX(3);
        
        
        driveTrainBackRight = new WPI_TalonSRX(4);
        
        
        driveTrainRightDrive = new SpeedControllerGroup(driveTrainFrontRight, driveTrainBackRight  );
        LiveWindow.addActuator("DriveTrain", "RightDrive", driveTrainRightDrive);
        
        driveTrainDifferentialDrive1 = new DifferentialDrive(driveTrainLeftDrive, driveTrainRightDrive);
        LiveWindow.addActuator("DriveTrain", "Differential Drive 1", driveTrainDifferentialDrive1);
        driveTrainDifferentialDrive1.setSafetyEnabled(true);
        driveTrainDifferentialDrive1.setExpiration(0.1);
        driveTrainDifferentialDrive1.setMaxOutput(1.0);
        
        leftEncoder = new Encoder(0, 1);
        rightEncoder = new Encoder(2, 3);

        powerManagmentPowerDistributionPanel = new PowerDistributionPanel(0);
        LiveWindow.addSensor("PowerManagment", "PowerDistributionPanel", powerManagmentPowerDistributionPanel);
        

        // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
    }
}
